### ISSUE TITLE
adapter wird nicht grün

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.digitalstrom#1]
Adapter 0.2.1 installiert, Token generiert, aber leider wird der Adapter nur Gelb und dann wieder rot
Daten holt er sich aber
 anbei das log
[iobroker.2020-01-13.log](https://github.com/ioBroker/ioBroker.digitalstrom/files/4053040/iobroker.2020-01-13.log)

**Comment by Apollon77** [comment]
Versuch mal bitte adapter per admin stoppen, kurz warten und neu starten ... den Fall hatten wir schonmal  ... ich verstehe ihn noch nicht.

Welcher js-controller?

**Comment by Apollon77** [comment]
PS: Der Effekt scheint aktuell primär zu passieren wenn der Adapter wegen Konfigänderungen und "save" automatisch neu gestartet wird

**Comment by Apollon77** [comment]
PPS: Kannst Du bitte mal das Log noch schicken vom allerersten Start bis zu dem zeitpunkt was Du jetzt geschickt hattest? Muss mal schauen was der controller da tut.

**Comment by Farmer-cb** [comment]
> Versuch mal bitte adapter per admin stoppen, kurz warten und neu starten ... den Fall hatten wir schonmal ... ich verstehe ihn noch nicht.
> 
> Welcher js-controller?

was verstehst du unter per admin stoppen??? Habe ihn per Instance-Übersicht gestoppt gestartet, kein erfolg, hab ihn per Console gestopt gestart auch keine änderung.

js-controller habe ich kurz zuvor upgedatet, ist aktuell 2.2.7

**Comment by Farmer-cb** [comment]
> PPS: Kannst Du bitte mal das Log noch schicken vom allerersten Start bis zu dem zeitpunkt was Du jetzt geschickt hattest? Muss mal schauen was der controller da tut.

das war das ganze log, von diesem Tag.
kann ich da irgendwas nochmal starten, damit du daten bekommst

**Comment by Apollon77** [comment]
Log vom ganzen Tag? kann nicht sein weil da fehlt mal mindestens der erste start nach der installation wo er sagt das er keinen token hat und so. ...

Also im Log sehe ich das der controller den Prozess wieder killt.

Ok, mach mal folgendes: Adapter stoppen. 60 Sekunden warten, dann adapter neu starten. Geht es dann?

**Comment by Apollon77** [comment]
PS: Der Effekt kommt wohl eher vom js-controller und liegt an der pot. recht langen Stop Zeit des Adapters ... also eher ein Bug im Controller. Mit den 60s warten sollte es aber tun denke ich.

**Comment by Farmer-cb** [comment]
> Log vom ganzen Tag? kann nicht sein weil da fehlt mal mindestens der erste start nach der installation wo er sagt das er keinen token hat und so. ...
> 
> Also im Log sehe ich das der controller den Prozess wieder killt.
> 
> Ok, mach mal folgendes: Adapter stoppen. 60 Sekunden warten, dann adapter neu starten. Geht es dann?

Habe leider das log nach dem Start gelöscht (war ein reflex).....
hab den Adapter jetzt seit mehr als 5min Aus, nach dem einschalten leider keine Änderung
hab das log per mail geschickt

**Comment by Apollon77** [comment]
Dann installier bitte nochmal neu vom Github ... version bleibt gleich, aber eine EInstellung ist anders. Damit besser?

**Comment by Apollon77** [comment]
Und das Log was Du geschickt hast war scheinbar das gleiche wie hier? ;-)

**Comment by Apollon77** [comment]
Suehe auch Email ... Bitte Geduld haben beim ersten Start .. kann dauern!!

**Comment by Farmer-cb** [comment]
hattest recht, kaum wartet man gefühlte 15min schon ist der Adapter grün, man darf sich nur nicht vom Wechsel rot gelb rot gelb täuschen lassen

**Comment by Apollon77** [comment]
Passiert das rot-gelb-rot-gelb auch wenn Du jetzt nochmal neu startest oder ist er dann schneller?

Bzw wenn ja bitte klapp im Admin mal "system.adapter.digitalstrom.0" auf und schau während dessen mal den "alive" state an ... geht der auf "null/leer oder false"?

**Comment by Farmer-cb** [comment]
adapter geht von rot auf gelb dann wieder rot und nach laaaanger zeit auf grün
im system.adapter.digitalstrom.0 muss ich noch gucken.


Habe aktuell das Problem:

> 

digitalstrom.0 | 2020-01-13 15:26:54.861 | warn | (18234) Too many event polling errors, restarting adapter
-- | -- | -- | --
digitalstrom.0 | 2020-01-13 15:26:54.861 | warn | (18234) Err: polling Event buttonClick (1): {"error":null,"status_code":500}
digitalstrom.0 | 2020-01-13 15:26:54.747 | warn | (18234) Too many event polling errors, restarting adapter

und das kommt am laufenden band
(brauchst die aktuelle Log wieder??)

**Comment by Apollon77** [comment]
Hm ... dann macht die DSS dicht und nimmt keine Anfragen mehr an :-( . Ja komplettes Log bitte nochmal.

Und versuch mal ob es generell tut wenn du die beiden Optionen (data-polling und werte anfragen) deaktivierst ... und vllt schau ob Du noch irgendwelche Skripte hast die zusätzlich die DSS belasten die Du deaktivieren kannst?

**Comment by Apollon77** [comment]
Ok, hab ne Vermutung wegen dem error 500 nach einiger zeit ... Bitte 0.2.2 vom GitHub versuchen obs besser ist

**Comment by Farmer-cb** [comment]
hab jetzt mal den alive beobachtet, beim einschalten ist alive true und connected true, nach kurzer zeit hat connected keinen wert mehr, alive bleibt die ganze zeit true.
Das ganze dauert ca 300s biss dann wieder connected ist

**Comment by Farmer-cb** [comment]
bis jetzt hatte ich keine error 500 meldung mehr, dafür aber die Meldung

> 19587) --INVALID {"name":"deviceBinaryInputEvent","properties":{"inputState":"0","inputIndex":"1","inputType":"12"},"source":{"set":"dsid(3a1c8e11734b5c32c02bea08aaad674f00)","dsid":"3a1c8e11734b5c32

**Comment by Farmer-cb** [comment]
hatte bis jetzt keine error 500 Meldung mehr dafür aber diese

`19587) --INVALID {"name":"deviceBinaryInputEvent","properties":{"inputState":"0","inputIndex":"1","inputType":"12"},"source":{"set":"dsid(3a1c8e11734b5c32c02bea08aaad674f00)","dsid":"3a1c8e11734b5c32`

**Comment by Apollon77** [comment]
Alles klar. Die liegt daran das ich selbst sowas nicht habe. Checke nachher. Bitte ab jetzt aber eigene issues für neue Dinge anlegen ;-))

**Comment by Apollon77** [comment]
Die --INVALID Meldung wird in nächster Version gefixt sein
