### ISSUE TITLE
Status der Enocean Fenstersensoren Typ: EnOcean single contact (D5-00-01)

### ISSUE THREAD

**Issue by BA2000** [ioBroker/ioBroker.digitalstrom#12]
Es scheint, dass der Bug noch nicht gefixt ist.
Im Plan44 bekomme ich die Stati 0/1 für die Fenstersensoren angezeigt, leider wird durch den ioBroker.digitalstrom V2.05 nur die Stati 1/2 angezeigt.
Was zur Folge natürlich falsche Anzeigen der Widgets hat, nämlich gekippt statt geschlossen, geöffnet stimmt aber. 
Dieser Sensor kann nur offen(0) oder geschlossen(1) feststellen, da es sich nicht um einen Fenstergriff mit 3 Stati handelt.

Gruss BA2000

**Comment by Apollon77** [comment]
Ne es ist abders... Die Stati in ioBroker fangen bei 1 an.

damit 0=1, 1=2, 2=3

Passt das?

Hintergrund hier ist das beim auseinandernehmen die DSS bei einem Call die Werte beginnende mit 0 und an anderer Stelle beginnend mit 1 (also um eins verschoben) rausgegeben hat und ich musste mich für eins der beiden entscheiden. Da beginnend mit 1 besser zu States der DSS an anderen Stellen in der Doku gepasst hat habe ich mich für 1.. entschieden.

**Comment by Apollon77** [comment]
relevant ist das es konstistent ist - also wenn die Zahlen zu den State werten (offen/geschlossen) pssen ist ja alles ok. Dann must Du "nur" die Werte ummappen das 0=1 und 1=2 bei dir ist
