### ISSUE TITLE
State value wrong

### ISSUE THREAD

**Issue by robertfraefel** [ioBroker/ioBroker.digitalstrom#143]
Still having a lot of reports in the Logs about wrong value state

**Versions:**  
 - Adapter version: 2.3.0
 - JS-Controller version: 3.3.18
 - Node version: v12.22.6
 - Operating system: Linux
 
![Screenshot 2021-11-03 at 10 45 17](https://user-images.githubusercontent.com/33721995/140040165-bfae297b-79ee-49ca-a4d6-bfb967be0a95.png)

**Comment by Apollon77** [comment]
duplicate #113 ... It would be great to get a full debug log from adapterstart to check.

Please get logfile from disk /opt/iobroker/logs/... and send via email to iobroker@fischer-ka.de
