### ISSUE TITLE
Nach Neustart des Adapters keine korrekten Sensordaten

### ISSUE THREAD

**Issue by gnomy** [ioBroker/ioBroker.digitalstrom#15]
Seit der Umstellung der Sensorwerte von booleans auf Zahlen werde diese nach einem Neustart des Adapters nicht richtig erkannt. Nach dem Neustart werden die Werte bei mir nicht geupdatet. Das führt dann zum Beispiel dazu, dass obwohl alle Fenster geschlossen sind, Skripte bei den der Status geprüft wird, nicht erkennen das die Fenster geschlossen sind. Ich muss dann zunächst alle Fenster einmal öffnen und wieder schließen. Danach funktionieren auch die Skripte wieder. Das selbe Problem habe ich mit dem Bewegeungssensor. Auch dort muss ich erst einmal den Sensor auslösen, bevor er dann wieder richtig das Licht an und aus schaltet.

**Comment by Apollon77** [comment]
Welche Version nutzt du?

**Comment by gnomy** [comment]
Na klar sorry hat ich vergessen dazu zuschreiben 2.05. Das Problem habe ich aber seit der Umstellung von true/ false auf das Binare System.

**Comment by Apollon77** [comment]
Bitte mal GitHub version testen

**Comment by gnomy** [comment]
Immer noch das selbe Problem. Alle Fenster werden als offen (1) angezeigt. Erst wenn man sie einmal öffnet und wieder schließt, wird der Staus als geschlossen (2) angezeigt.

**Comment by Apollon77** [comment]
Dann bitte:
- Adapter logging auf debug stellen
- Adapter starten und warten bis grün
- dann ein fenster nacheinander in die einzelnen zustände bringen
 Von jedem Schritt bitte die Zeitpunkte aufschreiben damit ich mich im log nicht dämlich suche

Dann alles in ein email mit verweis auf das issue hier an iobroker@fischer-ka.de senden

**Comment by gnomy** [comment]
Habe ich raus geschickt. Vielen Dank schon mal.
