### ISSUE TITLE
Token Fehler

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/ioBroker.digitalstrom#16]
Hallo bekomme seid kurzen diesen Fehler:
Queued entry ERROR device/getOutputValue and {"dsuid":"303505d7f8000000000000400003d11600","offset":0,"category":"manual","token":"9c33df68b8e0c0942530cb256aeb154e325c61082583cb7a805dd23be0fe

Habe schön einen neuen token erstellt.Aber genau das selbe.

**Comment by Apollon77** [comment]
Bitte mehr log zeigen

**Comment by Trunks1982** [comment]
<img width="1754" alt="Bildschirmfoto 2020-06-07 um 16 02 24" src="https://user-images.githubusercontent.com/62701386/83970876-6474cd00-a8d8-11ea-8a39-65085fd5fb6f.png">

**Comment by Apollon77** [comment]
Please get the full log from The logfile on disk. Admin is cutting lines

**Comment by Trunks1982** [comment]
Hab dir mal was rüber geschickt.Logge aber jetzt auch mal den debug modus mit.

**Comment by Trunks1982** [comment]
https://github.com/ioBroker/ioBroker.digitalstrom/issues/16#issuecomment-640230997

Mit freundlichen Grüßen

Christoph Badurczyk
