### ISSUE TITLE
Szenen (Stimmungen) mit Nr

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.digitalstrom#2]
Wäre es möglich, das nicht die einzelnen LichtSzenen (Stimmungen) angezeigt werden, sondern die Nr der LichtSzene die gerade aktiv ist.
Wohnzimmer Lichtszene 1 (für Stimmung 1)

so wie es aktuell angezeigt wird, ist es wenig sinnvoll, da ja eh nur immer eine Stimmung aktiv sein kann, ausser bei Bereichen

oder so lassen wie es ist und zusäztlich im Ordner scene die Nr anzeigen
z.b. digitalstrom.0.apartment.2.24.1.scenes hier die SceneNr

**Comment by Apollon77** [comment]
Die Szenenummern sind aber die Internen. Ich habe gerade keine Idee wie ich an andere Bezeichner rankommen kann. Das hier ist das Mapping ... https://github.com/ioBroker/ioBroker.digitalstrom/blob/master/lib/constants.js#L441 Also die nummern würdest Du bekommen. Wenn wäre die Idee einen Datenpunkt "lastSceneId" oder so anzulegen und da die Nummer reinzuschreiben. Wäre halt "5" für Stimmung 1 (Preset 1) als Beispiel (https://github.com/ioBroker/ioBroker.digitalstrom/blob/master/lib/constants.js#L485)

Hilf das?

Was genau willst Du damit tun?

**Comment by Farmer-cb** [comment]
ich finde es einfacher zur Anzeige, da ich nicht aus den 4 True/False Anweisungen (Stimmungen) rumsuchen muss, genau so wäre es am einfachsten wenn man auch so die Stimmung setzen könnte.
Aktuell müsste ich ja 4 einzelne Buttons für jeweils 1 Stimmung programmieren
genauso müsste ich ja 4 Lampenicons  für jeweils 1 Stimmung programmieren.

so habe ich es bis jetzt zumindest gemacht

kann natürlich sein das ich gerade ein Gedankenproblem habe.

**Comment by Strobelix80** [comment]
Für die Steuerung in VIS legst du einfach einem Datenpunkt an.
Wenn Datenpunkt True Steuere Preset 1 wahr
Wenn Datenpunkt false Steuere Preset 0 wahr.
Die Nummern aus der APi verwirren die meisten wohl eher, die die API nicht kennen.
Für die VIS muss man ja eh immer einen kleinen Umweg gehen

**Comment by Apollon77** [comment]
Also wie gesagt man kann Gern noch einen zusätzlichen scene state machen wir man eine Nummer reinschreiben kann könnte dann parallel gehen und wird auch immer aktualisiert.  Wenn es euch hilft geht das. Sagt was. Im Admin wäre das ein zahlenfeld mit bestimmten erlaubten Werten. Die dann sogar als selection im Admin angezeigt wird. Per JavaScript mit dem korrekten Zahlenwert beschreibbar.

**Comment by Strobelix80** [comment]
Ok dann gerne 😉

**Comment by Apollon77** [comment]
Kommt nachher in 0.3.0 ... dauert aber noch bissl. melde mich im Forum!
