### ISSUE TITLE
Neue Geräte

### ISSUE THREAD

**Issue by Trunks1982** [ioBroker/ioBroker.digitalstrom#21]
Hi,
könntest du neue Geräte die es von DS gibt neu hinzufügen?
UMR
UMV
dann sind neue Werte hinzugekommen wie Azimut der Sonne und Elevation.
Da meckert der Adapter immer das er die nicht kennt.
Wenn du ein Log brauchst kann ich dir gerne zukommen lassen.

**Comment by Apollon77** [comment]
Ja bitte. Ohne Log kann ich nix tun ... wenn du noch irgendwelche anderen Docs, Datasheets und so hast helfen die auch. Bitte volles Debug log am besten. email an iobroker@fischer-ka.de mit Referenz auf dieses issue hier (sonst weiss ich das in paar Tagen nimmer)

**Comment by Trunks1982** [comment]
Sehr gut ist gerade an dich raus

**Comment by Trunks1982** [comment]
Hast du mal nachgeguckt?

**Comment by Apollon77** [comment]
Noch keine Zeit gehabt

**Comment by Apollon77** [comment]
Ok, Ich habe das Log geprüft. Was genau ist das Thema mit den neuen geräten. Sie werden angelegt im Adapter .. Was gernau geht denn nicht?
AUch die sun azimut und so ist laut Log alles da.

AM besten bitte nochmal mit der Github version prüfen (nach install manuell neu starten)
