### ISSUE TITLE
Solltemperatur auslesen

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.digitalstrom#22]
Servus
besteht noch die Möglichkeit, das man die Solltemperatur mit ausliest und dementsprechend vielleicht bei den Sonoren in den entsprechenden Räumen anzeigt.
aktuell frage ich den wert per 
"https://dss_ip:8080/json/zone/getTemperatureControlStatus?token="+sesToken+"&name="+raumname+"""
ab

**Comment by Apollon77** [comment]
Also in den Daten gibt  es den NominalValue ... ich denke du meinst den... der ist leider in den Specs vpm DSS nicht virkloich beschrieben. Vor allem keine Ahnung ob der auch aktualisiert wird.

Ich habe Ihn auf der GitHub Verison mal eingebaut. Bitte testen und auch ob er aktualisiert wird.
