### ISSUE TITLE
Wrong temperature since latest ds update

### ISSUE THREAD

**Issue by adultano** [ioBroker/ioBroker.digitalstrom#220]
I habe a couple of temperature / humidity sensors i digitalstrom (enocean). Since the latest ds update (May 19th) I receive wrong temperatures in iobroker. In the ds system it shows the correct floating point number (e.g 23.994) but the object in iobroker shows 152.55. Anyone else seeing this - idea how to fix?

Thanks

**Comment by Apollon77** [comment]
Please turn on debug log for the instance and post the debug log for such values coming in ... what is "the latest ds update? Version number?

**Comment by adultano** [comment]
Actually it seems its already wrong in Digitalstrom. I receive wrong values from p44 bridge into Digitalstrom. So this issue can be closed. Sorry for the inconvenience. Thanks

**Comment by Apollon77** [comment]
Thank you for the feedback!
