### ISSUE TITLE
State issues since dSS Update 1.19.3 - state wrong

### ISSUE THREAD

**Issue by tmycgn** [ioBroker/ioBroker.digitalstrom#221]
It seems that since the update to [version 1.19.3](https://www.digitalstrom.com/wp-content/uploads/2022/05/SRN-2204_v1.0_EN-1.pdf) the states of lights are no longer represented correctly. Example:

I have two simple light bulbs (each via GE-KM300) in one room. Both lights can be switched individually via app and adapter state true/false. This still works correctly. However, if I **switch on** only **one** physical light switch or via the Digitalstrom app, the state of **both** lights **will be set to true** in ioBroker. (digitalstrom.0.devices.xxx.state)

Further tests indicated that this is independent of the connected DS hardware (f.e. GE-KM300 and GE-KL200), it will change the status of all devices connected in the room wrongly.

Who has faced similar problems since a few days?

```
- Platform linux
- Modell ARMv7 Processor rev 3 (v7l)
- Node.js v14.19.3
- NPM 6.14.14
- ioBroker 5.4.9
- Digitalstrom Adapter 2.3.0
```

I have the same behavior in all groups. I have already reset the iobroker object tree, restarted the dss server and adapters several times without improvement. Who can help that I can finally use my light again? :)

**Comment by Apollon77** [comment]
please provide a full debug log ... or in fact you can check in taht log and see what "changes" DS delivers". is there anything in the changelog that might have caused that ( I did not checked yet)

**Comment by tmycgn** [comment]
I had suspected that it might have something to do with the GE-KM300, since many changes have been made there. Therefore, I had already tested another scenario with different hardware (GE-KL200). Otherwise, I do not recognize anything conspicuous.

The debug results in an interesting case.... Here I just pressed one light switch via the app. If I understand the debug correctly, but the states of both lights are set to "on" correct?

![image](https://user-images.githubusercontent.com/82310796/170726347-c0f9b170-9119-4958-8c52-91c897773d25.png)

Setup:

![image](https://user-images.githubusercontent.com/82310796/170726758-67277927-7e25-4c0e-93eb-c6262152fbdf.png)

If the debug returns the values of the API, would this mean that the API has a bug in the new version?

**Comment by Apollon77** [comment]
The debug log means that there is a callScene event coming in for a zone and so the adapter sets the states to what he "guesses" and is pushing a "getOutputValue" to the queue to get the real real value.

To check this in detail I need a full debug log and time to dig through allll the details. If these two devices are not in the group for which the callscene command was sent then it is wrong that both are set ... but then data in the basic structuire wpuld be wrong because the adapter gets that on startup.

SO get a full debug log of start and then do such an action ... control via iobroker and also control outside and such. Then get logfile from disk (/opt/iobroker/log/...) and attach here or send to iobroker@fischer-ka.de via email with refernce to this issue

**Comment by tmycgn** [comment]
Thanks for your support, email with log and test details has been sent.

**Comment by tmycgn** [comment]
Hi @Apollon77, 

Since the Digitalstrom integration currently still does not work properly, I have tested further and found out the following. Maybe this leads to a solution of the problem. I have tested with the attached adapter configuration:

_Data Polling Interval: **60** - Use Scene Preset Values: **false** - Request Device Output values actively: **false**_

**Result:**

- If I press the **virtual switch** in the **Digitalstrom app**, the state* of the light is changed correctly with a slight time delay. The physical light is switched correctly.
- If I press the **physical switch**, the state* of the light is not changed at all. However, the physical light is switched correctly.


*_digitalstrom.0.devices.302ed89f43f0000000002c8000000c7600.302ed89f43f00000000045400052ab2600.state_

**Debug:**

_Switching the light via the Digitalstrom app:_

![image](https://user-images.githubusercontent.com/82310796/174451318-fa931c13-fa9a-47e1-b745-07e076fedfdb.png)

The status is then corrected with a slight time delay (2-10 seconds) when the following is executed with a time delay:

![image](https://user-images.githubusercontent.com/82310796/174451350-52094121-8590-4a06-adc5-34381e7aa6ae.png)

_Switching the lamp via the physical switch:_

![image](https://user-images.githubusercontent.com/82310796/174451373-7828fdc2-3805-431c-9160-96209638db1d.png)

Is there anything else I can do to support? Is the above configuration best-practise or should or should I change it for this issue?

Thanks!

**Comment by tmycgn** [comment]
The issue still exists. :/
