### ISSUE TITLE
String instead of number

### ISSUE THREAD

**Issue by Stefan200583** [ioBroker/ioBroker.digitalstrom#27]
Ein paar Werte sind als String anstatt als zahl definiert. Habe ich gerade beim neu Einlesen im Log gefunden:

digitalstrom.0 | 2021-01-11 12:26:35.265 | warn | (21963) This value will not be set in future versions. Please report this to the developer.
-- | -- | -- | --
digitalstrom.0 | 2021-01-11 12:26:35.265 | warn | (21963) State value to set is invalid for digitalstrom.0.apartment.sensors.outdoor.sunelevation: The state property "ts" has the wrong type "string" (should be "number")!
digitalstrom.0 | 2021-01-11 12:26:35.255 | warn | (21963) This value will not be set in future versions. Please report this to the developer.
digitalstrom.0 | 2021-01-11 12:26:35.254 | warn | (21963) State value to set is invalid for digitalstrom.0.apartment.sensors.outdoor.sunazimuth: The state property "ts" has the wrong type "string" (should be "number")!
digitalstrom.0 | 2021-01-11 12:26:35.249 | warn | (21963) This value will not be set in future versions. Please report this to the developer.
digitalstrom.0 | 2021-01-11 12:26:35.249 | warn | (21963) State value to set is invalid for digitalstrom.0.apartment.sensors.outdoor.temperature: The state property "ts" has the wrong type "string" (should be "number")!

**Comment by Apollon77** [comment]
Please enabe debug log that I can see which exact state caused this

**Comment by Apollon77** [comment]
Please try GitHub version, should be fixed

**Comment by Stefan200583** [comment]
Seems go be fixed. No warnings anymore. Thank you very much.
