### ISSUE TITLE
Benutzerdefinierte Handlung

### ISSUE THREAD

**Issue by 123Trunks** [ioBroker/ioBroker.digitalstrom#3]
Hi ist es möglich noch die Benutzdefinierten Handlung mit auszulesen?

**Comment by Apollon77** [comment]
Was wäre denn die Idee - Anzeige und die Möglichkeit die Handlung zu triggern und die option das man sieht ob/das sie getriggert wurde?

**Comment by Apollon77** [comment]
Ok, Event selbst raisen geht wohl ... auslesen auch

2020-01-14 22:59:31.543  - debug: digitalstrom.0 (23219) UNHANDLED EVENT: highlevelevent: {"name":"highlevelevent","properties":{"id":"1579039134"},"source":{"set":".zone(0).group(0)","groupID":0,"zoneID":0,"isApartment":true,"isGroup":false,"isDevice":false}}

Erkennen das es ausgelöst wurde durch die Bedingung geht wohl nicht !

**Comment by 123Trunks** [comment]
Hi der Adapter wird immer noch nicht grün.Benutzerdefinierte Handlung sind nur zum triggern da ob getriggert würde kann man generell nicht sehn.

⁣BlueMail for Android herunterladen ​

**Comment by 123Trunks** [comment]
Ah jetzt ist grün.😂

⁣BlueMail for Android herunterladen ​

**Comment by Apollon77** [comment]
Er braucht manchmal lange - vor allem bei grossen Installationen.

Ok, auslesen und triggern von user actions kriegen wir denke ich hin

**Comment by 123Trunks** [comment]
👍.Ist denn auch geplant das man andere Geräte und ds integrieren kann?
Sowas wie nen vdc?

⁣BlueMail for Android herunterladen ​

**Comment by Apollon77** [comment]
Ist das nicht ein neues Issue?! ;-)
Also an sich werden alle devices ausgelsen und angezeigt wenn Sie "isPresent" und "isValid" sind. Pro dsm/circuit/vDC gibt es unter "devices" einen Ordner wo diese Devices dann drin sind. Es sollten damit alle Dinge funktionieren wie bei den anderen Devices. Die STeuerung per Scenen und Sensor-Events und so sollten tun wenn Sie gesendet werden

Daher bitte ggf extra Issues mit exakten Infos was fehlt wenn was fehlt. Effektiv gibt es meines Wissens nach keine Doku wie man wirklich an die Output values rankommt ... der Adapter versucht bei Devices von "unbekanntem ds/vDC (also nicht yellow, gray)" UND einem output Value den Wert von offset 0 zu lesen und auf offset 0 zu schreiben ... das geht seit der 0.3.0 und muss mal getestet werden, da habe ich noch null Feedback.

Aber jetzt bitte: Für generelle Fragen bitte den verlinkten Forum Thread nutzen, da ist es einfacher sich auszutauschen :-) Oder zielgerichtet mit Details Feature Request GitHub issues anlegen :-)

In dem Issue hier geht es um user defined actions :-)

**Comment by Apollon77** [comment]
Bitte 0.4.0 checken auf GitHub
