### ISSUE TITLE
Adapter 0.3.1

### ISSUE THREAD

**Issue by 123Trunks** [ioBroker/ioBroker.digitalstrom#4]
Hallo seid dem ich den neuen Adapter installiert habe wird er nicht mehr grün.Hab ein wenig gewartet und neu gestartet keine Chance.

**Comment by Farmer-cb** [comment]
Bei mir das selbe

**Comment by 123Trunks** [comment]
Habe IObroker nochmals Neugestalten das selbe.

**Comment by Apollon77** [comment]
Ich habe einen Fehler gefunden ... 0.3.2 kommt gleich

**Comment by Apollon77** [comment]
0.3.2 on GitHub, pease check!
