### ISSUE TITLE
Adapter startet nicht

### ISSUE THREAD

**Issue by Krobi134** [ioBroker/ioBroker.digitalstrom#7]
Adapter 1.0.1 installiert
JS-Controller 2.2.8

Der Adapter startet nur mit einer Fehlermeldung im Log: 
(7102) Error while initializing Data: Error on query user-defined-states: [object Object]

Werte (Objekte) werden keine angelegt

Log im Anhang (debug)

[digitalstrom_log.txt](https://github.com/ioBroker/ioBroker.digitalstrom/files/4177782/digitalstrom_log.txt)

**Comment by Apollon77** [comment]
Hast du dir user defined states Erweiterung aktiv/installiert?

**Comment by Krobi134** [comment]
Bewusst hab ich das nicht aktiviert. 
Ich wüsste nicht an welcher Stelle ich die im dss finde.

**Comment by Apollon77** [comment]
Das ist eins der Plugins aufbauen allerersten Tab bei den Apps. Aber ok lass ich schaue mal.

**Comment by Apollon77** [comment]
Bitte installier mal neu vom GitHub ... (Version bleibt 1.0.1 ...) Tuts jetzt?

**Comment by Krobi134** [comment]
Habs neu installiert, Adapter startet. 
Super vielen Dank!!

Ich hab auch nochmal nachgesehen, ich hab keine user defined states aktiv oder eingestellt.

Im Log stehen noch paar Fehler 

[Digitalstrom_log.txt](https://github.com/ioBroker/ioBroker.digitalstrom/files/4182374/Digitalstrom_log.txt)

**Comment by Apollon77** [comment]
Die Polling Fehler können kommen wenn sich die session ändert ... die werden aber direkt neu initialisiert, von daher ok.

Die invalid state change können an sich nur kommen wenn neue states da sind die es am anfang nicht gab oder die zu irgendeiner besonderen zone gehören die nicht sauber kondofiguriert ist. 

Wenn DU die nicht brauchst würde ich es dabei belassen :-) Wenn Du sieh brauchst brauche ich volles Debug log vom Adapterstarte
