### ISSUE TITLE
falscher status der devices (enocean)

### ISSUE THREAD

**Issue by Farmer-cb** [ioBroker/ioBroker.digitalstrom#8]
jedesmal wenn der digitalstromadapter neu gestartet wird, werden die Devicestatus der Enocean-Bridge falsch gesetzt, in jeden 
digitalstrom.0.devices.xxxx.yyyy.binaryInputs.0 steht true drinn, bei fenstergriffen steht aber 0,1 oder 2 drinn

digitalstrom.0.devices.xxxx.yyyy.states.0 steht true drinn, bei Fenstergriffen oder Fenstersensoren steht aber open,tilted, oder closed drinn

dementsprechend sollte auch der Typ (hier boolean) verkehrt sein (müsste doch eigentlich number sein)
`{
  "type": "state",
  "common": {
    "name": "Window is tilted",
    "type": "boolean",
    "read": true,
    "write": false
  },
  "native": {},
  "from": "system.adapter.digitalstrom.0",
  "user": "system.user.admin",
  "ts": 1581940472582,
  "_id": "digitalstrom.0.devices.xxxxx.yyyyy.binaryInputs.0",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

im digitalstromserver stehen die Werte richtig

das Problem daran, ich muss nach jedem Start durchs Haus laufen und jeden sensor betätigen.

brauchst du irgendwelche logs dazu???

**Comment by Apollon77** [comment]
Bitte volles Debug log vom Adapterstart posten ode rmit per email an iobroker@fischer-ka.de (mit Referenz auf das issue und am besten beispiel Device IDs und so)

**Comment by Farmer-cb** [comment]
ist unterwegs

**Comment by Apollon77** [comment]
Oooohkkk ...
* binaryInputs I can convert to a number and then it shows 0,1 or 2 depending on the value
* some states are now strings ...

BREAKING! Daher 2.0.0 Bitte mal GitHub Verison installieren 2.0

**Comment by Farmer-cb** [comment]
mit der V2.0.0 ist zwar der Typ von binaryInputs auf Number, der angezeigte Status (Nr 1) ist aber nicht der aktuelle Status (Nr 0), komischerweise stimmt aber der states, da steht closed.
Wenn ich den Sensor betätigt habe ist 
0 : closed
1 : open
2 : tilted

nach den Start vor dem Sensor betätigen
1 : closed

**Comment by Apollon77** [comment]
Debug Log bitte von initial und vor allem dann änderungen und wieder das Device nennen

**Comment by Farmer-cb** [comment]
frisches Log mit Version 2.0.0 ist per mail unterwegs

**Comment by Apollon77** [comment]
Aaaaaalso ... Log geschaut:
* 2020-02-24 16:21:57 init vom adapter binary state steht auf 1 von binary Kontakt laut JSON der DSS
* 2020-02-24 16:21:57  states auslesen bringt closed mit Wert 1
* 2020-02-24 16:22:04 ... gleiche Werte
* 2020-02-24 16:31:33  Event binary input auf 1
* 2020-02-24 16:31:33 State change ... wert 1 -> 2 (open)
* 2020-02-24 16:32:23 Event binary input auf 0
* 2020-02-24 16:32:23 State change 2 -> 1 (closed)

Ist für mich leider exakt wie auf deinen Screenshots. Das offizielle State sehe ich nie auf "tilted" :-(

**Comment by Apollon77** [comment]
Siehe email ... ein Log mit jedem Fensterzustand mal Adapterstarten wäre cool ... hab da ne "Idee"/"Befürchtung"

**Comment by Farmer-cb** [comment]
also 
1. adapter im Debug-Mode starten (Fenster ist geschlossen)
2. Fenster Auf
3. Fenster gekippt
4. Fenster zu
5. Log per mail senden

______________________________________________________________

mfg
Büchner Christian
Dietldorf 47
93133 Burglengenfeld
Mobil: 015772476055

**Comment by Apollon77** [comment]
Am besten wäre:
1. Fenster Auf
2. adapter im debug starten
3. Fenster zu
4. Adapter neustarten in debug
5. Fenster kippen
6. Log senden :)

**Comment by Apollon77** [comment]
Check 2.0.4 please on GitHub
